Update ci-cd.yml
(publish의)show pull command 삭제 

develop에서 debug 용으로 불필요하게 echo하던 것들 삭제함.

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -167,10 +167,7 @@ jobs:
           cache-from: type=gha
           cache-to: type=gha,mode=max
 
-      - name: Show pull command
-        run: |
-          echo "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_REPO }}:${{ env.APP }}-develop"
-          echo "docker run -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_REPO }}:${{ env.APP }}-develop"
+      # show pull command는 삭제했음. 
   deploy:
     name: deploy
     needs: publish
@@ -207,7 +204,7 @@ jobs:
               \"echo '$ENV_B64' | base64 -d > /home/ssm-user/infra/.env\",
               \"sudo chown ssm-user:ssm-user /home/ssm-user/infra/.env\",
               \"sudo -u ssm-user -H bash /home/ssm-user/infra/scripts/deploy.sh\"
-              ]" \
+            ]" \
             --query "Command.CommandId" \
             --output text)
   
@@ -222,25 +219,19 @@ jobs:
   
             echo "Current Status: $STATUS"
   
-            if [ "$STATUS" = "Success" ]; then
-              echo "Deployment succeeded!"
-              break
-            fi
-  
-            if [ "$STATUS" = "Failed" ] || \
-               [ "$STATUS" = "Cancelled" ] || \
-               [ "$STATUS" = "TimedOut" ]; then
-  
-              aws ssm get-command-invocation \
-                --command-id "$COMMAND_ID" \
-                --instance-id "${{ secrets.EC2_INSTANCE_ID }}"
-  
-              exit 1
-            fi
+            case "$STATUS" in
+              Success)
+                echo "Deployment succeeded!"
+                exit 0
+                ;;
+              Failed|Cancelled|TimedOut)
+                echo "::error::Deployment failed."
+                exit 1
+                ;;
+            esac
   
             sleep 5
           done
   
-          aws ssm get-command-invocation \
-            --command-id "$COMMAND_ID" \
-            --instance-id "${{ secrets.EC2_INSTANCE_ID }}"
+          echo "::error::Deployment timed out."
+          exit 1
